function varargout=sym_canul_mf(action,varargin)
%% Automatically generated with matlabFunction
% 
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'ntau'
   varargout{1}=1;
   return
  case 'tp_del'
   varargout{1}=0;
   return
  case 'maxorder'
   varargout{1}=5;
   return
  case 'directional_derivative'
   varargout{1}=0;
   return
end
ind=varargin{1};
order=varargin{2};
nout=varargin{3};
f=str2func(sprintf('sym_canul_mf_%s_%d_%d',action,ind,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{4:end});




function [out1,out2,out3] = sym_canul_mf_rhs_1_0(u1,u2,u3,u1t,u2t,u3t,a,tau)
%SYM_CANUL_MF_RHS_1_0
%    [OUT1,OUT2,OUT3] = SYM_CANUL_MF_RHS_1_0(U1,U2,U3,U1T,U2T,U3T,A,TAU)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    04-Oct-2025 02:09:38

t2 = u3.*(1.0./2.0e1);
t3 = t2+1.0;
t4 = 1.0./t3;
out1 = u1.*(-7.0./2.0e1)-u1.*(u1.*(1.0./1.5e2)-1.0).*(1.0./1.0e2)-t4.*u1.*u2.*(3.0./2.0e1)+2.0e1;
if nargout > 1
    out2 = -a.*u2-u2.*u3.*(8.0./5.0)+t4.*u1.*u2.*(3.0./2.0e1);
end
if nargout > 2
    out3 = u3.*(-9.0./2.0e1)-u2.*u3.*(1.0./1.0e2)+u2t.*u3t.*(1.0./5.0);
end


function [out1,out2,out3] = sym_canul_mf_rhs_1_1(u1,u2,u3,u1t,u2t,u3t,a,tau,u1_d,u2_d,u3_d,u1t_d,u2t_d,u3t_d,a_d,tau_d)
%SYM_CANUL_MF_RHS_1_1
%    [OUT1,OUT2,OUT3] = SYM_CANUL_MF_RHS_1_1(U1,U2,U3,U1T,U2T,U3T,A,TAU,U1_D,U2_D,U3_D,U1T_D,U2T_D,U3T_D,A_D,TAU_D)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    04-Oct-2025 02:09:38

t2 = u3.*(1.0./2.0e1);
t3 = t2+1.0;
t4 = 1.0./t3;
t5 = 1.0./t3.^2;
t6 = t5.*u1.*u2.*u3_d.*(3.0./4.0e2);
out1 = t6-u1_d.*(7.0./2.0e1)-u1_d.*(u1.*(1.0./1.5e2)-1.0).*(1.0./1.0e2)-u1.*u1_d.*6.666666666666667e-5-t4.*u1.*u2_d.*(3.0./2.0e1)-t4.*u2.*u1_d.*(3.0./2.0e1);
if nargout > 1
    out2 = -t6-a.*u2_d-a_d.*u2-u2.*u3_d.*(8.0./5.0)-u3.*u2_d.*(8.0./5.0)+t4.*u1.*u2_d.*(3.0./2.0e1)+t4.*u2.*u1_d.*(3.0./2.0e1);
end
if nargout > 2
    out3 = u3_d.*(-9.0./2.0e1)-u2.*u3_d.*(1.0./1.0e2)-u3.*u2_d.*(1.0./1.0e2)+u2t.*u3t_d.*(1.0./5.0)+u3t.*u2t_d.*(1.0./5.0);
end


function [out1,out2,out3] = sym_canul_mf_rhs_1_2(u1,u2,u3,u1t,u2t,u3t,a,tau,u1_d,u2_d,u3_d,u1t_d,u2t_d,u3t_d,u1_d_d,u2_d_d,u3_d_d,u1t_d_d,u2t_d_d,u3t_d_d,a_d,tau_d,a_d_d,tau_d_d)
%SYM_CANUL_MF_RHS_1_2
%    [OUT1,OUT2,OUT3] = SYM_CANUL_MF_RHS_1_2(U1,U2,U3,U1T,U2T,U3T,A,TAU,U1_D,U2_D,U3_D,U1T_D,U2T_D,U3T_D,U1_D_D,U2_D_D,U3_D_D,U1T_D_D,U2T_D_D,U3T_D_D,A_D,TAU_D,A_D_D,TAU_D_D)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    04-Oct-2025 02:09:38

t2 = u3.*(1.0./2.0e1);
t3 = t2+1.0;
t4 = 1.0./t3;
t5 = 1.0./t3.^2;
t6 = t5.*u1.*u2_d.*u3_d_d.*(3.0./4.0e2);
t7 = t5.*u1.*u3_d.*u2_d_d.*(3.0./4.0e2);
t8 = t5.*u2.*u1_d.*u3_d_d.*(3.0./4.0e2);
t9 = t5.*u2.*u3_d.*u1_d_d.*(3.0./4.0e2);
t10 = 1.0./t3.^3;
out1 = t6+t7+t8+t9-u1_d.*u1_d_d.*1.333333333333333e-4-t4.*u1_d.*u2_d_d.*(3.0./2.0e1)-t4.*u2_d.*u1_d_d.*(3.0./2.0e1)-t10.*u1.*u2.*u3_d.*u3_d_d.*7.5e-4;
if nargout > 1
    out2 = -t6-t7-t8-t9-a_d.*u2_d_d-a_d_d.*u2_d-u2_d.*u3_d_d.*(8.0./5.0)-u3_d.*u2_d_d.*(8.0./5.0)+t4.*u1_d.*u2_d_d.*(3.0./2.0e1)+t4.*u2_d.*u1_d_d.*(3.0./2.0e1)+t10.*u1.*u2.*u3_d.*u3_d_d.*7.5e-4;
end
if nargout > 2
    out3 = u2_d.*u3_d_d.*(-1.0./1.0e2)-u3_d.*u2_d_d.*(1.0./1.0e2)+u2t_d.*u3t_d_d.*(1.0./5.0)+u3t_d.*u2t_d_d.*(1.0./5.0);
end


function [out1,out2,out3] = sym_canul_mf_rhs_1_3(u1,u2,u3,u1t,u2t,u3t,a,tau,u1_d,u2_d,u3_d,u1t_d,u2t_d,u3t_d,u1_d_d,u2_d_d,u3_d_d,u1t_d_d,u2t_d_d,u3t_d_d,u1_d_d_d,u2_d_d_d,u3_d_d_d,u1t_d_d_d,u2t_d_d_d,u3t_d_d_d,a_d,tau_d,a_d_d,tau_d_d,a_d_d_d,tau_d_d_d)
%SYM_CANUL_MF_RHS_1_3
%    [OUT1,OUT2,OUT3] = SYM_CANUL_MF_RHS_1_3(U1,U2,U3,U1T,U2T,U3T,A,TAU,U1_D,U2_D,U3_D,U1T_D,U2T_D,U3T_D,U1_D_D,U2_D_D,U3_D_D,U1T_D_D,U2T_D_D,U3T_D_D,U1_D_D_D,U2_D_D_D,U3_D_D_D,U1T_D_D_D,U2T_D_D_D,U3T_D_D_D,A_D,TAU_D,A_D_D,TAU_D_D,A_D_D_D,TAU_D_D_D)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    04-Oct-2025 02:09:38

t2 = u3.*(1.0./2.0e1);
t3 = t2+1.0;
t4 = 1.0./t3.^2;
t5 = 1.0./t3.^3;
t6 = t4.*u1_d.*u2_d_d.*u3_d_d_d.*(3.0./4.0e2);
t7 = t4.*u1_d.*u3_d_d.*u2_d_d_d.*(3.0./4.0e2);
t8 = t4.*u2_d.*u1_d_d.*u3_d_d_d.*(3.0./4.0e2);
t9 = t4.*u2_d.*u3_d_d.*u1_d_d_d.*(3.0./4.0e2);
t10 = t4.*u3_d.*u1_d_d.*u2_d_d_d.*(3.0./4.0e2);
t11 = t4.*u3_d.*u2_d_d.*u1_d_d_d.*(3.0./4.0e2);
t12 = 1.0./t3.^4;
t13 = t12.*u1.*u2.*u3_d.*u3_d_d.*u3_d_d_d.*1.125e-4;
out1 = t6+t7+t8+t9+t10+t11+t13-t5.*u1.*u2_d.*u3_d_d.*u3_d_d_d.*7.5e-4-t5.*u1.*u3_d.*u2_d_d.*u3_d_d_d.*7.5e-4-t5.*u1.*u3_d.*u3_d_d.*u2_d_d_d.*7.5e-4-t5.*u2.*u1_d.*u3_d_d.*u3_d_d_d.*7.5e-4-t5.*u2.*u3_d.*u1_d_d.*u3_d_d_d.*7.5e-4-t5.*u2.*u3_d.*u3_d_d.*u1_d_d_d.*7.5e-4;
if nargout > 1
    out2 = -t6-t7-t8-t9-t10-t11-t13+t5.*u1.*u2_d.*u3_d_d.*u3_d_d_d.*7.5e-4+t5.*u1.*u3_d.*u2_d_d.*u3_d_d_d.*7.5e-4+t5.*u1.*u3_d.*u3_d_d.*u2_d_d_d.*7.5e-4+t5.*u2.*u1_d.*u3_d_d.*u3_d_d_d.*7.5e-4+t5.*u2.*u3_d.*u1_d_d.*u3_d_d_d.*7.5e-4+t5.*u2.*u3_d.*u3_d_d.*u1_d_d_d.*7.5e-4;
end
if nargout > 2
    out3 = 0.0;
end


function [out1,out2,out3] = sym_canul_mf_rhs_1_4(u1,u2,u3,u1t,u2t,u3t,a,tau,u1_d,u2_d,u3_d,u1t_d,u2t_d,u3t_d,u1_d_d,u2_d_d,u3_d_d,u1t_d_d,u2t_d_d,u3t_d_d,u1_d_d_d,u2_d_d_d,u3_d_d_d,u1t_d_d_d,u2t_d_d_d,u3t_d_d_d,u1_d_d_d_d,u2_d_d_d_d,u3_d_d_d_d,u1t_d_d_d_d,u2t_d_d_d_d,u3t_d_d_d_d,a_d,tau_d,a_d_d,tau_d_d,a_d_d_d,tau_d_d_d,a_d_d_d_d,tau_d_d_d_d)
%SYM_CANUL_MF_RHS_1_4
%    [OUT1,OUT2,OUT3] = SYM_CANUL_MF_RHS_1_4(U1,U2,U3,U1T,U2T,U3T,A,TAU,U1_D,U2_D,U3_D,U1T_D,U2T_D,U3T_D,U1_D_D,U2_D_D,U3_D_D,U1T_D_D,U2T_D_D,U3T_D_D,U1_D_D_D,U2_D_D_D,U3_D_D_D,U1T_D_D_D,U2T_D_D_D,U3T_D_D_D,U1_D_D_D_D,U2_D_D_D_D,U3_D_D_D_D,U1T_D_D_D_D,U2T_D_D_D_D,U3T_D_D_D_D,A_D,TAU_D,A_D_D,TAU_D_D,A_D_D_D,TAU_D_D_D,A_D_D_D_D,TAU_D_D_D_D)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    04-Oct-2025 02:09:39

t2 = u3.*(1.0./2.0e1);
t3 = t2+1.0;
t4 = 1.0./t3.^3;
t5 = 1.0./t3.^4;
t6 = t5.*u1.*u2_d.*u3_d_d.*u3_d_d_d.*u3_d_d_d_d.*1.125e-4;
t7 = t5.*u1.*u3_d.*u2_d_d.*u3_d_d_d.*u3_d_d_d_d.*1.125e-4;
t8 = t5.*u1.*u3_d.*u3_d_d.*u2_d_d_d.*u3_d_d_d_d.*1.125e-4;
t9 = t5.*u1.*u3_d.*u3_d_d.*u3_d_d_d.*u2_d_d_d_d.*1.125e-4;
t10 = t5.*u2.*u1_d.*u3_d_d.*u3_d_d_d.*u3_d_d_d_d.*1.125e-4;
t11 = t5.*u2.*u3_d.*u1_d_d.*u3_d_d_d.*u3_d_d_d_d.*1.125e-4;
t12 = t5.*u2.*u3_d.*u3_d_d.*u1_d_d_d.*u3_d_d_d_d.*1.125e-4;
t13 = t5.*u2.*u3_d.*u3_d_d.*u3_d_d_d.*u1_d_d_d_d.*1.125e-4;
t14 = 1.0./t3.^5;
out1 = t6+t7+t8+t9+t10+t11+t12+t13-t4.*u1_d.*u2_d_d.*u3_d_d_d.*u3_d_d_d_d.*7.5e-4-t4.*u1_d.*u3_d_d.*u2_d_d_d.*u3_d_d_d_d.*7.5e-4-t4.*u1_d.*u3_d_d.*u3_d_d_d.*u2_d_d_d_d.*7.5e-4-t4.*u2_d.*u1_d_d.*u3_d_d_d.*u3_d_d_d_d.*7.5e-4-t4.*u2_d.*u3_d_d.*u1_d_d_d.*u3_d_d_d_d.*7.5e-4-t4.*u2_d.*u3_d_d.*u3_d_d_d.*u1_d_d_d_d.*7.5e-4-t4.*u3_d.*u1_d_d.*u2_d_d_d.*u3_d_d_d_d.*7.5e-4-t4.*u3_d.*u1_d_d.*u3_d_d_d.*u2_d_d_d_d.*7.5e-4-t4.*u3_d.*u2_d_d.*u1_d_d_d.*u3_d_d_d_d.*7.5e-4-t4.*u3_d.*u2_d_d.*u3_d_d_d.*u1_d_d_d_d.*7.5e-4-t4.*u3_d.*u3_d_d.*u1_d_d_d.*u2_d_d_d_d.*7.5e-4-t4.*u3_d.*u3_d_d.*u2_d_d_d.*u1_d_d_d_d.*7.5e-4-t14.*u1.*u2.*u3_d.*u3_d_d.*u3_d_d_d.*u3_d_d_d_d.*2.25e-5;
if nargout > 1
    out2 = -t6-t7-t8-t9-t10-t11-t12-t13+t4.*u1_d.*u2_d_d.*u3_d_d_d.*u3_d_d_d_d.*7.5e-4+t4.*u1_d.*u3_d_d.*u2_d_d_d.*u3_d_d_d_d.*7.5e-4+t4.*u1_d.*u3_d_d.*u3_d_d_d.*u2_d_d_d_d.*7.5e-4+t4.*u2_d.*u1_d_d.*u3_d_d_d.*u3_d_d_d_d.*7.5e-4+t4.*u2_d.*u3_d_d.*u1_d_d_d.*u3_d_d_d_d.*7.5e-4+t4.*u2_d.*u3_d_d.*u3_d_d_d.*u1_d_d_d_d.*7.5e-4+t4.*u3_d.*u1_d_d.*u2_d_d_d.*u3_d_d_d_d.*7.5e-4+t4.*u3_d.*u1_d_d.*u3_d_d_d.*u2_d_d_d_d.*7.5e-4+t4.*u3_d.*u2_d_d.*u1_d_d_d.*u3_d_d_d_d.*7.5e-4+t4.*u3_d.*u2_d_d.*u3_d_d_d.*u1_d_d_d_d.*7.5e-4+t4.*u3_d.*u3_d_d.*u1_d_d_d.*u2_d_d_d_d.*7.5e-4+t4.*u3_d.*u3_d_d.*u2_d_d_d.*u1_d_d_d_d.*7.5e-4+t14.*u1.*u2.*u3_d.*u3_d_d.*u3_d_d_d.*u3_d_d_d_d.*2.25e-5;
end
if nargout > 2
    out3 = 0.0;
end


function [out1,out2,out3] = sym_canul_mf_rhs_1_5(u1,u2,u3,u1t,u2t,u3t,a,tau,u1_d,u2_d,u3_d,u1t_d,u2t_d,u3t_d,u1_d_d,u2_d_d,u3_d_d,u1t_d_d,u2t_d_d,u3t_d_d,u1_d_d_d,u2_d_d_d,u3_d_d_d,u1t_d_d_d,u2t_d_d_d,u3t_d_d_d,u1_d_d_d_d,u2_d_d_d_d,u3_d_d_d_d,u1t_d_d_d_d,u2t_d_d_d_d,u3t_d_d_d_d,u1_d_d_d_d_d,u2_d_d_d_d_d,u3_d_d_d_d_d,u1t_d_d_d_d_d,u2t_d_d_d_d_d,u3t_d_d_d_d_d,a_d,tau_d,a_d_d,tau_d_d,a_d_d_d,tau_d_d_d,a_d_d_d_d,tau_d_d_d_d,a_d_d_d_d_d,tau_d_d_d_d_d)
%SYM_CANUL_MF_RHS_1_5
%    [OUT1,OUT2,OUT3] = SYM_CANUL_MF_RHS_1_5(U1,U2,U3,U1T,U2T,U3T,A,TAU,U1_D,U2_D,U3_D,U1T_D,U2T_D,U3T_D,U1_D_D,U2_D_D,U3_D_D,U1T_D_D,U2T_D_D,U3T_D_D,U1_D_D_D,U2_D_D_D,U3_D_D_D,U1T_D_D_D,U2T_D_D_D,U3T_D_D_D,U1_D_D_D_D,U2_D_D_D_D,U3_D_D_D_D,U1T_D_D_D_D,U2T_D_D_D_D,U3T_D_D_D_D,U1_D_D_D_D_D,U2_D_D_D_D_D,U3_D_D_D_D_D,U1T_D_D_D_D_D,U2T_D_D_D_D_D,U3T_D_D_D_D_D,A_D,TAU_D,A_D_D,TAU_D_D,A_D_D_D,TAU_D_D_D,A_D_D_D_D,TAU_D_D_D_D,A_D_D_D_D_D,TAU_D_D_D_D_D)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    04-Oct-2025 02:09:39

t2 = u3.*(1.0./2.0e1);
t3 = t2+1.0;
t4 = 1.0./t3.^4;
t5 = 1.0./t3.^5;
t6 = t4.*u1_d.*u2_d_d.*u3_d_d_d.*u3_d_d_d_d.*u3_d_d_d_d_d.*1.125e-4;
t7 = t4.*u1_d.*u3_d_d.*u2_d_d_d.*u3_d_d_d_d.*u3_d_d_d_d_d.*1.125e-4;
t8 = t4.*u1_d.*u3_d_d.*u3_d_d_d.*u2_d_d_d_d.*u3_d_d_d_d_d.*1.125e-4;
t9 = t4.*u1_d.*u3_d_d.*u3_d_d_d.*u3_d_d_d_d.*u2_d_d_d_d_d.*1.125e-4;
t10 = t4.*u2_d.*u1_d_d.*u3_d_d_d.*u3_d_d_d_d.*u3_d_d_d_d_d.*1.125e-4;
t11 = t4.*u2_d.*u3_d_d.*u1_d_d_d.*u3_d_d_d_d.*u3_d_d_d_d_d.*1.125e-4;
t12 = t4.*u2_d.*u3_d_d.*u3_d_d_d.*u1_d_d_d_d.*u3_d_d_d_d_d.*1.125e-4;
t13 = t4.*u2_d.*u3_d_d.*u3_d_d_d.*u3_d_d_d_d.*u1_d_d_d_d_d.*1.125e-4;
t14 = t4.*u3_d.*u1_d_d.*u2_d_d_d.*u3_d_d_d_d.*u3_d_d_d_d_d.*1.125e-4;
t15 = t4.*u3_d.*u1_d_d.*u3_d_d_d.*u2_d_d_d_d.*u3_d_d_d_d_d.*1.125e-4;
t16 = t4.*u3_d.*u1_d_d.*u3_d_d_d.*u3_d_d_d_d.*u2_d_d_d_d_d.*1.125e-4;
t17 = t4.*u3_d.*u2_d_d.*u1_d_d_d.*u3_d_d_d_d.*u3_d_d_d_d_d.*1.125e-4;
t18 = t4.*u3_d.*u2_d_d.*u3_d_d_d.*u1_d_d_d_d.*u3_d_d_d_d_d.*1.125e-4;
t19 = t4.*u3_d.*u2_d_d.*u3_d_d_d.*u3_d_d_d_d.*u1_d_d_d_d_d.*1.125e-4;
t20 = t4.*u3_d.*u3_d_d.*u1_d_d_d.*u2_d_d_d_d.*u3_d_d_d_d_d.*1.125e-4;
t21 = t4.*u3_d.*u3_d_d.*u1_d_d_d.*u3_d_d_d_d.*u2_d_d_d_d_d.*1.125e-4;
t22 = t4.*u3_d.*u3_d_d.*u2_d_d_d.*u1_d_d_d_d.*u3_d_d_d_d_d.*1.125e-4;
t23 = t4.*u3_d.*u3_d_d.*u2_d_d_d.*u3_d_d_d_d.*u1_d_d_d_d_d.*1.125e-4;
t24 = t4.*u3_d.*u3_d_d.*u3_d_d_d.*u1_d_d_d_d.*u2_d_d_d_d_d.*1.125e-4;
t25 = t4.*u3_d.*u3_d_d.*u3_d_d_d.*u2_d_d_d_d.*u1_d_d_d_d_d.*1.125e-4;
t26 = 1.0./t3.^6;
t27 = t26.*u1.*u2.*u3_d.*u3_d_d.*u3_d_d_d.*u3_d_d_d_d.*u3_d_d_d_d_d.*5.625e-6;
out1 = t6+t7+t8+t9+t10+t11+t12+t13+t14+t15+t16+t17+t18+t19+t20+t21+t22+t23+t24+t25+t27-t5.*u1.*u2_d.*u3_d_d.*u3_d_d_d.*u3_d_d_d_d.*u3_d_d_d_d_d.*2.25e-5-t5.*u1.*u3_d.*u2_d_d.*u3_d_d_d.*u3_d_d_d_d.*u3_d_d_d_d_d.*2.25e-5-t5.*u1.*u3_d.*u3_d_d.*u2_d_d_d.*u3_d_d_d_d.*u3_d_d_d_d_d.*2.25e-5-t5.*u1.*u3_d.*u3_d_d.*u3_d_d_d.*u2_d_d_d_d.*u3_d_d_d_d_d.*2.25e-5-t5.*u1.*u3_d.*u3_d_d.*u3_d_d_d.*u3_d_d_d_d.*u2_d_d_d_d_d.*2.25e-5-t5.*u2.*u1_d.*u3_d_d.*u3_d_d_d.*u3_d_d_d_d.*u3_d_d_d_d_d.*2.25e-5-t5.*u2.*u3_d.*u1_d_d.*u3_d_d_d.*u3_d_d_d_d.*u3_d_d_d_d_d.*2.25e-5-t5.*u2.*u3_d.*u3_d_d.*u1_d_d_d.*u3_d_d_d_d.*u3_d_d_d_d_d.*2.25e-5-t5.*u2.*u3_d.*u3_d_d.*u3_d_d_d.*u1_d_d_d_d.*u3_d_d_d_d_d.*2.25e-5-t5.*u2.*u3_d.*u3_d_d.*u3_d_d_d.*u3_d_d_d_d.*u1_d_d_d_d_d.*2.25e-5;
if nargout > 1
    out2 = -t6-t7-t8-t9-t10-t11-t12-t13-t14-t15-t16-t17-t18-t19-t20-t21-t22-t23-t24-t25-t27+t5.*u1.*u2_d.*u3_d_d.*u3_d_d_d.*u3_d_d_d_d.*u3_d_d_d_d_d.*2.25e-5+t5.*u1.*u3_d.*u2_d_d.*u3_d_d_d.*u3_d_d_d_d.*u3_d_d_d_d_d.*2.25e-5+t5.*u1.*u3_d.*u3_d_d.*u2_d_d_d.*u3_d_d_d_d.*u3_d_d_d_d_d.*2.25e-5+t5.*u1.*u3_d.*u3_d_d.*u3_d_d_d.*u2_d_d_d_d.*u3_d_d_d_d_d.*2.25e-5+t5.*u1.*u3_d.*u3_d_d.*u3_d_d_d.*u3_d_d_d_d.*u2_d_d_d_d_d.*2.25e-5+t5.*u2.*u1_d.*u3_d_d.*u3_d_d_d.*u3_d_d_d_d.*u3_d_d_d_d_d.*2.25e-5+t5.*u2.*u3_d.*u1_d_d.*u3_d_d_d.*u3_d_d_d_d.*u3_d_d_d_d_d.*2.25e-5+t5.*u2.*u3_d.*u3_d_d.*u1_d_d_d.*u3_d_d_d_d.*u3_d_d_d_d_d.*2.25e-5+t5.*u2.*u3_d.*u3_d_d.*u3_d_d_d.*u1_d_d_d_d.*u3_d_d_d_d_d.*2.25e-5+t5.*u2.*u3_d.*u3_d_d.*u3_d_d_d.*u3_d_d_d_d.*u1_d_d_d_d_d.*2.25e-5;
end
if nargout > 2
    out3 = 0.0;
end

