function varargout=sym_canul(action,varargin)
%% Automatically generated with matlabFunction
% 
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'ntau'
   varargout{1}=1;
   return
  case 'tp_del'
   varargout{1}=0;
   return
  case 'maxorder'
   varargout{1}=5;
   return
  case 'directional_derivative'
   varargout{1}=1;
   return
end
ind=varargin{1};
order=varargin{2};
nout=varargin{3};
f=str2func(sprintf('sym_canul_%s_%d_%d',action,ind,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{4:end});




function [out1,out2,out3] = sym_canul_rhs_1_0(u1,u2,u3,u1t,u2t,u3t,a,tau,u1_d,u2_d,u3_d,u1t_d,u2t_d,u3t_d,a_d,tau_d)
%SYM_CANUL_RHS_1_0
%    [OUT1,OUT2,OUT3] = SYM_CANUL_RHS_1_0(U1,U2,U3,U1T,U2T,U3T,A,TAU,U1_D,U2_D,U3_D,U1T_D,U2T_D,U3T_D,A_D,TAU_D)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    04-Oct-2025 02:09:40

t2 = u3.*(1.0./2.0e1);
t3 = t2+1.0;
t4 = 1.0./t3;
out1 = u1.*(-7.0./2.0e1)-u1.*(u1.*(1.0./1.5e2)-1.0).*(1.0./1.0e2)-t4.*u1.*u2.*(3.0./2.0e1)+2.0e1;
if nargout > 1
    out2 = -a.*u2-u2.*u3.*(8.0./5.0)+t4.*u1.*u2.*(3.0./2.0e1);
end
if nargout > 2
    out3 = u3.*(-9.0./2.0e1)-u2.*u3.*(1.0./1.0e2)+u2t.*u3t.*(1.0./5.0);
end


function [out1,out2,out3] = sym_canul_rhs_1_1(u1,u2,u3,u1t,u2t,u3t,a,tau,u1_d,u2_d,u3_d,u1t_d,u2t_d,u3t_d,a_d,tau_d)
%SYM_CANUL_RHS_1_1
%    [OUT1,OUT2,OUT3] = SYM_CANUL_RHS_1_1(U1,U2,U3,U1T,U2T,U3T,A,TAU,U1_D,U2_D,U3_D,U1T_D,U2T_D,U3T_D,A_D,TAU_D)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    04-Oct-2025 02:09:40

t2 = u3.*(1.0./2.0e1);
t3 = t2+1.0;
t4 = 1.0./t3;
t5 = 1.0./t3.^2;
t6 = t5.*u1.*u2.*u3_d.*(3.0./4.0e2);
out1 = t6-u1_d.*(7.0./2.0e1)-u1_d.*(u1.*(1.0./1.5e2)-1.0).*(1.0./1.0e2)-u1.*u1_d.*6.666666666666667e-5-t4.*u1.*u2_d.*(3.0./2.0e1)-t4.*u2.*u1_d.*(3.0./2.0e1);
if nargout > 1
    out2 = -t6-a.*u2_d-a_d.*u2-u2.*u3_d.*(8.0./5.0)-u3.*u2_d.*(8.0./5.0)+t4.*u1.*u2_d.*(3.0./2.0e1)+t4.*u2.*u1_d.*(3.0./2.0e1);
end
if nargout > 2
    out3 = u3_d.*(-9.0./2.0e1)-u2.*u3_d.*(1.0./1.0e2)-u3.*u2_d.*(1.0./1.0e2)+u2t.*u3t_d.*(1.0./5.0)+u3t.*u2t_d.*(1.0./5.0);
end


function [out1,out2,out3] = sym_canul_rhs_1_2(u1,u2,u3,u1t,u2t,u3t,a,tau,u1_d,u2_d,u3_d,u1t_d,u2t_d,u3t_d,a_d,tau_d)
%SYM_CANUL_RHS_1_2
%    [OUT1,OUT2,OUT3] = SYM_CANUL_RHS_1_2(U1,U2,U3,U1T,U2T,U3T,A,TAU,U1_D,U2_D,U3_D,U1T_D,U2T_D,U3T_D,A_D,TAU_D)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    04-Oct-2025 02:09:40

t2 = u3.*(1.0./2.0e1);
t3 = t2+1.0;
t4 = 1.0./t3.^2;
t5 = 1.0./t3;
t6 = t4.*u1.*u2_d.*u3_d.*(3.0./2.0e2);
t7 = t4.*u2.*u1_d.*u3_d.*(3.0./2.0e2);
t8 = u3_d.^2;
t9 = 1.0./t3.^3;
out1 = t6+t7-u1_d.^2.*1.333333333333333e-4-t5.*u1_d.*u2_d.*(3.0./1.0e1)-t8.*t9.*u1.*u2.*7.5e-4;
if nargout > 1
    out2 = -t6-t7-a_d.*u2_d.*2.0-u2_d.*u3_d.*(1.6e1./5.0)+t5.*u1_d.*u2_d.*(3.0./1.0e1)+t8.*t9.*u1.*u2.*7.5e-4;
end
if nargout > 2
    out3 = u2_d.*u3_d.*(-1.0./5.0e1)+u2t_d.*u3t_d.*(2.0./5.0);
end


function [out1,out2,out3] = sym_canul_rhs_1_3(u1,u2,u3,u1t,u2t,u3t,a,tau,u1_d,u2_d,u3_d,u1t_d,u2t_d,u3t_d,a_d,tau_d)
%SYM_CANUL_RHS_1_3
%    [OUT1,OUT2,OUT3] = SYM_CANUL_RHS_1_3(U1,U2,U3,U1T,U2T,U3T,A,TAU,U1_D,U2_D,U3_D,U1T_D,U2T_D,U3T_D,A_D,TAU_D)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    04-Oct-2025 02:09:40

t2 = u3_d.^2;
t3 = u3.*(1.0./2.0e1);
t4 = t3+1.0;
t5 = 1.0./t4.^3;
t6 = 1.0./t4.^2;
t7 = t6.*u1_d.*u2_d.*u3_d.*(9.0./2.0e2);
t8 = 1.0./t4.^4;
t9 = t2.*t8.*u1.*u2.*u3_d.*1.125e-4;
out1 = t7+t9-t2.*t5.*u1.*u2_d.*2.25e-3-t2.*t5.*u2.*u1_d.*2.25e-3;
if nargout > 1
    out2 = -t7-t9+t2.*t5.*u1.*u2_d.*2.25e-3+t2.*t5.*u2.*u1_d.*2.25e-3;
end
if nargout > 2
    out3 = 0.0;
end


function [out1,out2,out3] = sym_canul_rhs_1_4(u1,u2,u3,u1t,u2t,u3t,a,tau,u1_d,u2_d,u3_d,u1t_d,u2t_d,u3t_d,a_d,tau_d)
%SYM_CANUL_RHS_1_4
%    [OUT1,OUT2,OUT3] = SYM_CANUL_RHS_1_4(U1,U2,U3,U1T,U2T,U3T,A,TAU,U1_D,U2_D,U3_D,U1T_D,U2T_D,U3T_D,A_D,TAU_D)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    04-Oct-2025 02:09:40

t2 = u3_d.^2;
t3 = u3.*(1.0./2.0e1);
t4 = t3+1.0;
t5 = 1.0./t4.^4;
t6 = t2.^2;
t7 = 1.0./t4.^5;
t8 = t2.*t5.*u1.*u2_d.*u3_d.*4.5e-4;
t9 = t2.*t5.*u2.*u1_d.*u3_d.*4.5e-4;
t10 = 1.0./t4.^3;
out1 = t8+t9-t6.*t7.*u1.*u2.*2.25e-5-t2.*t10.*u1_d.*u2_d.*(9.0./1.0e3);
if nargout > 1
    out2 = -t8-t9+t6.*t7.*u1.*u2.*2.25e-5+t2.*t10.*u1_d.*u2_d.*(9.0./1.0e3);
end
if nargout > 2
    out3 = 0.0;
end


function [out1,out2,out3] = sym_canul_rhs_1_5(u1,u2,u3,u1t,u2t,u3t,a,tau,u1_d,u2_d,u3_d,u1t_d,u2t_d,u3t_d,a_d,tau_d)
%SYM_CANUL_RHS_1_5
%    [OUT1,OUT2,OUT3] = SYM_CANUL_RHS_1_5(U1,U2,U3,U1T,U2T,U3T,A,TAU,U1_D,U2_D,U3_D,U1T_D,U2T_D,U3T_D,A_D,TAU_D)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    04-Oct-2025 02:09:40

t2 = u3_d.^2;
t3 = t2.^2;
t4 = u3.*(1.0./2.0e1);
t5 = t4+1.0;
t6 = 1.0./t5.^5;
t7 = 1.0./t5.^6;
t8 = t3.*t7.*u1.*u2.*u3_d.*5.625e-6;
t9 = 1.0./t5.^4;
t10 = t2.*t9.*u1_d.*u2_d.*u3_d.*2.25e-3;
out1 = t8+t10-t3.*t6.*u1.*u2_d.*1.125e-4-t3.*t6.*u2.*u1_d.*1.125e-4;
if nargout > 1
    out2 = -t8-t10+t3.*t6.*u1.*u2_d.*1.125e-4+t3.*t6.*u2.*u1_d.*1.125e-4;
end
if nargout > 2
    out3 = 0.0;
end

